import { AiFillStar } from "react-icons/ai"

const data = [
  {
    Id:"1",
    img: "./img/products/f1.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "Flower shirt",
  },
  {
    Id:"2",
    img: "./img/products/f2.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"3",
    img: "./img/products/f3.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"4",
    img: "./img/products/f4.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "Flower shirt",
  },
  {
    Id:"5",
    img: "./img/products/f5.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "Flower shirt",
  },
  {
    Id:"6",
    img: "./img/products/f6.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"7",
    img: "./img/products/f7.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"8",
    img: "./img/products/f8.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"9",
    img: "./img/products/n1.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
   {
    Id:"10",
    img: "./img/products/n2.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"11",
    img: "./img/products/n3.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"12",
    img: "./img/products/n4.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"13",
    img: "./img/products/n5.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"14",
    img: "./img/products/n6.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"15",
    img: "./img/products/n7.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"16",
    img: "./img/products/n8.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
]

export default data