import { AiFillStar } from "react-icons/ai"

const shopdata = [
  {
    Id:"1",
    img: "./img/products/f1.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "Flower shirt",
  },
  {
    Id:"2",
    img: "./img/products/f2.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"3",
    img: "./img/products/f3.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"4",
    img: "./img/products/f4.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "Flower shirt",
  },
  {
    Id:"5",
    img: "./img/products/f5.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "Flower shirt",
  },
  {
    Id:"6",
    img: "./img/products/f6.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"7",
    img: "./img/products/f7.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
  {
    Id:"8",
    img: "./img/products/f8.jpg",
    title: "Cartoon Astrinaut T-shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    Price: "200",
    color: "white",
    category: "sneakers",
  },
]
export default shopdata